# bin2c.cmake — embed a binary file as a C byte array.
#
# Invoked via:  cmake -DINPUT=<file> -DOUTPUT=<file.c> -DSYMBOL=<name> -P bin2c.cmake
#
# Emits a .c (C linkage, external) defining:
#     const unsigned char <SYMBOL>[]      = { ... };
#     const unsigned int  <SYMBOL>_len    = <N>;
#
# Compiled as C, the symbols are unmangled; declare them from C++ with extern "C".

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hexlen)
math(EXPR len "${hexlen} / 2")

# "414243" -> "0x41,0x42,0x43," ; wrap every 16 bytes for readable output.
string(REGEX REPLACE "(..)" "0x\\1," body "${hex}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n  " body "${body}")

file(WRITE  "${OUTPUT}" "/* Generated by bin2c.cmake — do not edit. Source: ${INPUT} */\n")
file(APPEND "${OUTPUT}" "const unsigned char ${SYMBOL}[] = {\n  ${body}\n};\n")
file(APPEND "${OUTPUT}" "const unsigned int ${SYMBOL}_len = ${len}u;\n")
